language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U setuptools; sudo apt-get install tidy python3-uno; pip install -r requirements.txt ; pip install .; libreoffice '--accept=socket,host=127.0.0.1,port=8100;urp;' &
# command to run tests, e.g. python setup.py test
script:  export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache ; mkdir $LINO_CACHE_ROOT; inv initdb test

